version: '3'

services:
  db:
    image: postgres:9.5
    ports:
      - '127.0.0.1:5432:5432'
  #redis:
    #image: redis
    #ports:
     # - '127.0.0.1:6379:6379'
  # search:
    # image: elasticsearch:2.4
    # ports:
    #   - '127.0.0.1:9200:9200'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9099
    environment:
      - DATABASE_URL=postgres://namoxpanel:namoxpanel@db/namoxpanel
      - DEFAULT_FROM_EMAIL=noreply@namoxpanel.com
    #  - ELASTICSEARCH_URL=http://search:9200/
    #  - OPENEXCHANGERATES_API_KEY
    #  - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=changeme
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=rtt4leia4_rbe(t)h1k1o#8jgl-*nyc60fh3nto0zr**hmq=o@
      - DOCKER_CONTAINER=True
    depends_on:
      - db
      #- redis
      #- search
